server:
  contextPath: /server-config
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wmifsud/cars-config
          search-paths:
            - 'commercial'
            - 'sports'
            - 'suv'
  profiles:
      active: sports

greeting: main app hello